### ISSUE TITLE
Feedback & Suggestions

### ISSUE THREAD

**Issue by Mhowser** [LambdAurora/LambdaControls#1]
Here is a list of items (gathered from Discord) that could be implemented for better user experience.
(not in any particular order)

![](https://cdn.discordapp.com/attachments/507304429255393324/654577587493797888/unknown.png)

- [ ] The controls menu is too high and not centered

- [x] I suggest shortening `Controls mode:` to just `mode:` to prevent text going out of bounds

- [x] The link for the `SDL2 Gamepad Tool` should be clickable (open in browser)

- [x] The location to put the gamepad mappings should originate from `.minecraft` (e.g `.minecraft/config/x.txt`)

- [x] Ability to reload the gamepad DB without restarting the game

- [x] Use arrow-style navigation for menus instead of TAB-style

- [x] Auto select the controller when plugged in, and revert to previous input when the controller is unplugged (a toggle to enable / disable this behavior as well)

- [x] Ability for 'Full Keyboard Gameplay' (e.g camera movement control using Numpad)

- [x] Be able to tap a hotbar slot to select it in Touchscreen mode

Thanks a lot for making this mod! **ITS AWESOME!!**

**Comment by Mhowser** [comment]
- [ ] [BUG] The D-Pad Down button takes 2 screenshots instead of 1

**Comment by Mhowser** [comment]
Here are some new bugs I found:

- [ ] only `gamepadtool` is clickable in the URL (there should also be a highlight when hovered over to indicate that its a clickable link) 
![image](https://user-images.githubusercontent.com/24195572/70735195-922edf80-1cc2-11ea-9b0d-f08231f7ec6f.png)
 

- [ ] The left and right look bindings are reversed (e.g setting `left arrow` for `look left` makes camera look right, etc.)

- [ ] Using keyboard look bindings results in mouse-based camera movement not working
https://streamable.com/bbqo6

**Comment by LambdAurora** [comment]
I fixed the 3 latest bugs!

**Comment by Mhowser** [comment]
i did `git pull` but it says its already up to date, where are the bugfixes?

**Comment by LambdAurora** [comment]
Forgot to push, my bad!

**Comment by LambdAurora** [comment]
> The controls menu is too high and not centered

This may not be fixed as it's vanilla behavior for the button list widget, you can see the same thing for the mouse settings for example.

**Comment by Mhowser** [comment]
I have an idea regarding that, you could fill in that empty space with a controller graphic like this (example) ![image](https://user-images.githubusercontent.com/24195572/70867920-c78c3500-1f2f-11ea-9c1c-2865940edf36.png) and when a user presses an input, the graphic will highlight that input.

**Comment by LambdAurora** [comment]
Sadly, that won't be possible, it's very hard to add (and non-needed I think).

The thing is, the way Minecraft manages the GUI makes impossible to add that, and auto GUI Scale already fill all of the space.

**Comment by LambdAurora** [comment]
As someone who plays with a GUI Scale 3, there's not enough space for it: 
![2019-12-15_21-46](https://user-images.githubusercontent.com/12587332/70868802-7ce8d800-1f84-11ea-94cc-51da9c4bdd48.png)

**Comment by Mhowser** [comment]
ah, i forgot about the GUI scale

**Comment by LambdAurora** [comment]
As I added everything and fixed everything (except for the GUI centering which isn't fixable), I'm closing this issue.
