### ISSUE TITLE
Analog input for movements

### ISSUE THREAD

**Issue by LambdAurora** [LambdAurora/LambdaControls#10]
**Is your feature request related to a problem? Please describe.**
Support for analog input for movements.

**Describe the solution you'd like**
If the movements buttons are analog, then use the analog input.

**Comment by Mhowser** [comment]
An ability to choose between analog and vanilla style movement would be
good to as well.

**Comment by LambdAurora** [comment]
Ok, I'll do it, thanks ^^

**Comment by Mhowser** [comment]
Thank you!

**Comment by NyaomiDEV** [comment]
I don't know if #3 is related to what I am describing here, but analog input should be used for camera movement as well. Right now, doing diagonal movements with the camera is not precise and, overall, a pain. It's plain better to look at an object by adjusting the view horizontally and then vertically, but it is not as natural to do.

**Comment by LambdAurora** [comment]
Well, camera movements are already analog, but the speed and fluidity is currently frame-rate dependent. I should look at it, but honestly the camera code is kind of a mess.

**Comment by machinesmith42** [comment]
is this in the latest?

**Comment by LambdAurora** [comment]
what do you mean?

**Comment by machinesmith42** [comment]
is analog movement in the latest build?

**Comment by LambdAurora** [comment]
Analog movement no, analog camera yes.

I'll try to add the analog movement for the next release.

**Comment by LambdAurora** [comment]
Analog movements has been added to [LambdaControls v1.4.0](https://www.curseforge.com/minecraft/mc-mods/lambdacontrols/files/3008323).
