### ISSUE TITLE
Feature Request: Separate cursor for controller

### ISSUE THREAD

**Issue by Jarfeh** [LambdAurora/LambdaControls#12]
There was an older joystick mod for Minecraft, that ceased to be updated after 1.12.2, and it allowed the use of a separate cursor, completely disconnected from Windows' cursor. As it currently stands, if you have two clients open, one using keyboard and mouse, and another with a controller, only one can access the inventory at a time, due to them both sharing the windows cursor

**Comment by LambdAurora** [comment]
I'm aware of this problem, I might add that feature into the mod, but I can't tell you when.

If you don't mind playing with Forge for the moment (which I don't recommend for split screen as it takes more resources) you could try with MrCrayfish's Controllable mod which has this feature.

**Comment by LambdAurora** [comment]
Good news, this has been added in 1.2.0 for 1.15.2 and in 1.3.0 for 1.16.1!
