### ISSUE TITLE
Pickup

### ISSUE THREAD

**Issue by TheStarTraveler** [LambdAurora/LambdaControls#13]
**Describe the bug**
The pick up all function doesn't work unless you do pick up on the object first then pick up all

**To Reproduce**
1. Hover over a stack of items
2. Press the button that you use for pick up all
3. it won't let you pick it up

**Expected behavior**
Should be able to press pick up all on an item to be able to pick it up

**Desktop (please complete the following information):**
 - OS: (Windows 10)
 - Minecraft (1.16.1)
 - Fabric (fabric-api- 0.14.0+build.371-1.16)

**Comment by LambdAurora** [comment]
Fixed with v1.3.1!
