### ISSUE TITLE
Crash when pressing L1 in survival inventory

### ISSUE THREAD

**Issue by mrmangohands** [LambdAurora/LambdaControls#16]
**Describe the bug**
Pressing L1 on a dualshock 4 in survival inventory causes the game to crash

**Desktop:**
 - OS: Windows 10
 - Minecraft: 1.16.1
 - Fabric: fabric 0.8.8+build.202
 - Mods: fabric-api-0.14.0+build.371-1.16, lambdacontrols-fabric-1.3.2+1.16.1
 - Version: 1.3.2

**Additional context**
Here's a [log](https://paste.ee/p/Prj5v) from a fresh multimc instance

**Comment by LambdAurora** [comment]
Hello, I isolated the crash and I'll fix it for the next release.

Until then, to prevent the crash unlock at least 1 recipe and it mays require for the recipe book to be open.

**Comment by LambdAurora** [comment]
Fixed it in [LambdaControls v1.4.0](https://www.curseforge.com/minecraft/mc-mods/lambdacontrols/files/3008323).
