### ISSUE TITLE
Crash when run with REI

### ISSUE THREAD

**Issue by rosareven** [LambdAurora/LambdaControls#17]
**Describe the bug**
Running Minecraft with LambdaControls and REI together will result in a crash, without the Minecraft loading screen appearing at all.

**To Reproduce**
1. Setup a modded Minecraft instance with Fabric Loader, Fabric API, REI and LambdaControls.
2. Launch the instance.
3. Game crashes before it is launched.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.16.1
 - Fabric 0.9.0+build.204
 - Mods:
![image](https://user-images.githubusercontent.com/17244066/87862698-f695d980-c94a-11ea-9a42-ca28cc925cee.png)

Crash log: https://paste.ee/p/kHsyj

**Comment by LambdAurora** [comment]
Should be fixed in [LambdaControls v1.4.1](https://www.curseforge.com/minecraft/mc-mods/lambdacontrols/files/3008555)!

**Comment by rosareven** [comment]
Woah what a speedy fix! Thank you, works fine now!
