### ISSUE TITLE
sprint and sneak don't have expected "Toggle" or "Hold" behaviors

### ISSUE THREAD

**Issue by pcal43** [LambdAurora/LambdaControls#19]
First off, thanks so much for making this mod.  It's so great to be able to have gamepad support on fabric.

**Describe the bug**

The Options | Accessibility Settings has settings for Toggle vs. Hold on both Sneak and Sprint.  These don't seem to be respected by the gamepad controls.

**To Reproduce**

When Sneaking, it seems to be permanently in "Toggle" mode - i.e. it does not respect the "Hold" setting on the Accessibility Settings.

When Sprinting, when I press the sprint button, I seem to just be stuck in sprint mode regardless of what I do with the sprint button.  I can cancel it by sneaking or running off a cliff.

**Expected behavior**

 If I have Sprint set to "Hold", sprinting will start when I press the sprint button and release when I release the button.  If I have it set to "Toggle", it should be press-on/press-off.  

Likewise for sneaking.

**Desktop (please complete the following information):**
 - OS: windows
 - Minecraft 1.16.1
 - Fabric 0.9.0+build204
 - Mods Lithium (server )
 - Version LambdaControls 1.4.1+1.6.1
 - Branch release

**Additional context**

Thanks again!

**Comment by LambdAurora** [comment]
Fixed in [LambdaControls v1.5.0](https://github.com/LambdAurora/LambdaControls/releases/tag/1.5.0) ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/lambdacontrols/files/3047242)).
