### ISSUE TITLE
The mouse tutorial toast ignores the controller's camera movement.

### ISSUE THREAD

**Issue by joaoh1** [LambdAurora/LambdaControls#2]
**Describe the bug**
The tutorial toast to look around isn't affected by the camera movement done with a controller.

**To Reproduce**
1. Run Minecraft for the first time or go to options.txt and set "tutorialStep" to movement
2. Create a new world with the controller connected
3. Move around to complete the first toast
4. Try to look around with the controller

**Expected behavior**
Looking around should get rid of that tutorial toast.

**Screenshots**
[Here's a GIF](http://i.imgur.com/kYYcTRqh.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft: 1.15.1
 - Fabric: fabric 0.7.2+build.175
 - Mods: lambdacontrols-1.0.0-fabric1.15, fabric-api-0.4.25+build.282-1.15
 - Version: 1.0.0
 - Branch: master

**Additional context**
While it might be a minor issue, it can be a bit of an annoyance when starting a new modpack for the first time.

**Comment by LambdAurora** [comment]
Fixed in version 1.0.1!
