### ISSUE TITLE
Ok Zoomer Breaks LambAControls and Reset Keys Button Crashes Minecraft

### ISSUE THREAD

**Issue by vulntsar** [LambdAurora/LambdaControls#23]
**Describe the bug**
When trying to reset a single button binding it crashes also with just this mod pressing reset keys also crashes minecraft

**To Reproduce(w/ Ok Zoomer)**
1. Go to 'Options'
2. Click on 'Controls...'
3. Change Button Binding'
4. Click on 'Reset' or 'Unbound'
5. See error

**To Reproduce(Without Ok Zoomer)**
1. Go to 'Options'
2. Click on 'Controls...'
3. Change Button Binding'
4. Click on 'Reset keys'
5. See error

**Expected behaviour(w/ Ok Zoomer) **
I Expected to reset a single button binding

**Expected behaviour(w/ Ok Zoomer) **
I Expected to reset all button bindings

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.16.1
 - Fabric Loader-0.9.1+build.205-1.16.1
 - Mods lambdacontrols-fabric-1.4.1+1.16.1 and fabric-api-0.17.0+build.386-1.16.1 (w/ or without Ok Zoomer)
 - Java Version: 1.8.0_51, Oracle Corporation
 - Branch normal

**Additional context**
Playing Minecraft with a Xbox One S Controller and Needing Certain Key bindings For Useful Tasks

**Comment by LambdAurora** [comment]
Fixed in [LambdaControls v1.5.0](https://github.com/LambdAurora/LambdaControls/releases/tag/1.5.0) ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/lambdacontrols/files/3047242)).
