### ISSUE TITLE
OptiFabric

### ISSUE THREAD

**Issue by Ceztio** [LambdAurora/LambdaControls#25]
Seems that you cant use OptiFabric and LambdaControls together.

Error msg:

Found conflicting mods: lambdacontrols breaks {optifabric @ [*]}
Creating Empty clause ?

**Comment by LambdAurora** [comment]
Won't fix, I don't want to deal with a deprecated mess, use alternatives: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754

**Comment by Ceztio** [comment]
Sorry! didn't see your new post.. Thanks, have a great Day/Night! ^^

**Comment by YTG1234** [comment]
if "breaks" appears in the error message, just know the mod won't fix it.
