### ISSUE TITLE
Virtual Mouse cannot interact with REI Recipes

### ISSUE THREAD

**Issue by FiddyOnFiddy** [LambdAurora/LambdaControls#26]
**Describe the bug**
I cannot select any of the items on REI on the right hand side using the controller. I can select it with the mouse and then click the "+" to craft and it'll work with the controller there but I cannot select the initial recipe with the controller mod and I cannot seem to figure how what's wrong.

**To Reproduce**

**Expected behavior**
Expected full compatibility with REI as I see no mention of the issue I'm experiencing anywhere.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.16.1 
 - fabric-api-0.17.0+build.386-1.16.1
 - Mods: All of Fabric 3 Modpack
 - Version 1.5.3
 - Branch Latest for this version

**Additional context**

**Comment by LambdAurora** [comment]
Fixed in [LambdaControls v1.5.0](https://github.com/LambdAurora/LambdaControls/releases/tag/1.5.0) ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/lambdacontrols/files/3047242)).
