### ISSUE TITLE
Independent stick dead zones?

### ISSUE THREAD

**Issue by Chocohead** [LambdAurora/LambdaControls#32]
I've been using 1.5.0 on 1.16.3 for reference, and have to say the experience as a whole is all pretty nice. Ever since the introduction of analogue support though for my particular controller at least I've found it hard to get the dead zone settings quite right. The left stick seems to need it very low or walking is slow, often slow enough to not even start running. I've found manually setting the dead zone even slightly negative up to -0.1 gets it closer to a normal keyboard input. Doing so is not a perfect fix however as the camera drifts from the right stick needing the dead zone to be much higher, normally anything above 0.1 is fine. I think it would be helpful if there was separate dead zone controls for different analogue inputs so they could be tuned as needed. Alternatively an option to boost the sensitivity like what the camera controls have would work, or even just an option to use analogue sticks as digital inputs.

**Comment by LambdAurora** [comment]
Independent stick dead zones are part of LambdaControls 1.6.0 now!
