### ISSUE TITLE
Incompatibility with BetterF3 mod

### ISSUE THREAD

**Issue by Rafii2198** [LambdAurora/LambdaControls#33]
(I opened an issue on their repository https://github.com/cominixo/BetterF3/issues/4)

TL;DR as the BetterF3 developer @cominixo said it seems that Lambda Controls uses an older version of NIghtConfig which makes the game crash after making any changes to the BetterF3 mod.

I think you both should discuss what to do.

**Comment by LambdAurora** [comment]
Fixed in [LambdaControls 1.6.0](https://github.com/LambdAurora/LambdaControls/releases/tag/1.6.0-1.16).
