### ISSUE TITLE
Boat bug

### ISSUE THREAD

**Issue by LambdAurora** [LambdAurora/LambdaControls#37]
**Describe the bug**
Boat with controller input is extremely broken.

 - Sinks
 - "paddle in circles and hilariously capsize."

**To Reproduce**
1. Use a boat with a controller

**Expected behavior**
Boat working properly, not randomly sinking, etc.

**Additional context**
Issue reported from [CF comments](https://www.curseforge.com/minecraft/mc-mods/lambdacontrols?comment=142)

**Comment by puzzlecube** [comment]
I have also had this bug happen too. Tested with Minecraft version 1.16.4 LambdaControls 1.5.0. Boats can also sink through solid blocks occasionally and can cause a boat to spaz out when riding in the back seat even while on a server. The passenger jitter does not have any server side effects though.
