### ISSUE TITLE
CTD unless Charm is Disabled

### ISSUE THREAD

**Issue by chosti-factor** [LambdAurora/LambdaControls#39]
Hello. I'm playing All of Fabric 3 and hoped to use this mod. Unfortunately, when the mod "Charm" is present, there is a CTD.
[Crash Report.txt](https://github.com/LambdAurora/LambdaControls/files/5640761/Crash.Report.txt)

**Comment by LambdAurora** [comment]
Fixed in [LambdaControls 1.6.0](https://github.com/LambdAurora/LambdaControls/releases/tag/1.6.0-1.16).
