### ISSUE TITLE
triple whammy

### ISSUE THREAD

**Issue by Yoghurt4C** [LambdAurora/LambdaControls#4]
1. pressing the right analogue does not toggle sneak (x360 controller used)
2. you're unable to "scroll" through your sent chat messages with arrow keys on a keyboard when the mod is installed
3(?). the controller button HUD is unusually hard on the general performance, tanking it by simply being present

there have also been complaints about nesting the vanilla controls menu under your own, which is actually quite wack
version control: `lambdacontrols-1.0.1-fabric1.15`

**Comment by LambdAurora** [comment]
Issues 1 and 2 are fixed in the latest commit, third is in progress and may require help from another developer as I don't see how to optimize the HUD rendering.

> there have also been complaints about nesting the vanilla controls menu under your own, which is actually quite wack

It's understandable, I originally found this easier to access with a controller, I will look into this and try to find a better way.

**Comment by LambdAurora** [comment]
Done in 1.1.0!
