### ISSUE TITLE
Movement is Always extremely slow

### ISSUE THREAD

**Issue by NinjolasNJM** [LambdAurora/LambdaControls#41]
**Describe the bug**
Using the stick to move only goes about a fourth or half of walking speed and it is impossible to sprint. I tried using the settings to fix this, but there doesn't seem to be an

**To Reproduce**
1. Use LambdaControls on Mac, with a Pro Controller
2. Use SDL gamepad tool linked in the game to get the controller working, and import the mapping
3. Go to a world and try to move
**Expected behavior**
I expected it to let you move normally, but it doesn't.

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.15.4
 - Minecraft 1.16.4
 - Fabric fabric 0.10.8- 1.16.4
 - Mods SPL, Ok Zoomer, worldedit, multiconnect, appleskin, litematica

**Comment by rbits0** [comment]
Same problem on Windows 10 Minecraft 1.16.5 with a Nintendo Switch Pro Controller

**Comment by E-Pony** [comment]
same on Pop_os minecraft 1.16.4 with switch Pro Controller

**Comment by LambdAurora** [comment]
Sorry to answer this late, but it seems like the max float value a pro controller yields for the axes is not 1 as it should be.

Will be fixed in next release with the introduction of an option to disable analog movement and an option to adjust the max values of the controller.

**Comment by LambdAurora** [comment]
Fixed in [LambdaControls 1.6.0](https://github.com/LambdAurora/LambdaControls/releases/tag/1.6.0-1.16) with the introduction of new settings.
