### ISSUE TITLE
touch screen is inverted

### ISSUE THREAD

**Issue by WesleyVanNeck** [LambdAurora/LambdaControls#42]
**Describe the bug**

**To Reproduce**
1. Go to controller settings
2. set it on touch mode
3. play the game
4. see its inverted

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Minecraft 1.16.5
 - Fabric 0.11.1
 - Mods onlylamda controls
 - Version latest
 - Branch latest release

**Additional context**

**Comment by LambdAurora** [comment]
Touch screen support is dropped.
