### ISSUE TITLE
Lambdacontrols causes error and game crash with latest ModMenu version

### ISSUE THREAD

**Issue by Mhowser** [LambdAurora/LambdaControls#43]
**Describe the bug**

When i click on the `mods` button, this error from lambdacontrols pops up:
[crash-2021-02-17_22.06.44-client.txt](https://github.com/LambdAurora/LambdaControls/files/6000616/crash-2021-02-17_22.06.44-client.txt)

If i go to Options > Controls > Options, the game crashes with the same error as before.

**Expected behavior**
No errors or crashes

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Zorin OS 15.3
 - Minecraft 1.16.5
 - Fabric 0.11.1
 - Mods see crash log for mods
 - Version LambdaControls 1.5.0+1.16.2
 - Branch 1.16

**Additional context**

**Comment by LambdAurora** [comment]
LambDynamicLights 1.3.3+ is incompatible with LambdaControls.

I have rewritten the whole GUI library I use so it broke stuff and I haven't had the necessary motivation yet to finish updating LambdaControls.

**Comment by Mhowser** [comment]
Oh i thought it was modmenus fault, I'll close this issue since there is already one about this.
