### ISSUE TITLE
weird issue with hypixel?!?!??!?

### ISSUE THREAD

**Issue by nonetrix** [LambdAurora/LambdaControls#47]
**Describe the bug**

**To Reproduce**
1. Install mod
2. Go to hypixel
3. Get kicked to limbo??!?!?!?

**Expected behavior**
Hypixel doesn't kick you to limbo and everything works fine

**Screenshots**

**Desktop (please complete the following information):**
 - OS: arch linux
 - 1.16.5
 - Fabric fabric loader-0.11.2-1.16.5
 - Mods disabled all mods to test if it was other mods
 - Version v1.5.0
 - Branch stable?

**Additional context**
log on joining the server
https://pastebin.com/PpeZRRzh

**Comment by Kichura** [comment]
This is confirmed on a windows 10 unit with the same mod installed. Upon joining the server forces the player to enter limbo instead due to some unexpected movement change or some code caused hypixel's bungeecord system to trigger a kick.

**Comment by LambdAurora** [comment]
Not an issue with the mod itself, it's Hypixel's doing I can't do anything about that, please report that to Hypixel instead.
