### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by itsbumble** [LambdAurora/LambdaControls#48]
**Describe the bug**
crash when clicking on options->controls->options

**To Reproduce**
1. Go to options/controls
2. Click on options
3. crash
4. 

**Expected behavior**
access config menu

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10
 - Minecraft 1.16.5
 - Fabric newest
 - Mods (ignore everything unchecked)
![image](https://user-images.githubusercontent.com/78655784/110547764-d3948180-80f5-11eb-9397-89124b5e5049.png)

 - Version newest
 - Branch curseforge

**Additional context**
CRASH LOG
[crash-2021-03-09_16.32.32-client.txt](https://github.com/LambdAurora/LambdaControls/files/6111814/crash-2021-03-09_16.32.32-client.txt)

**Comment by itsbumble** [comment]
ooo this seems to be a crash with lambdabettergrass 
maybe because i am using indium ?????????????

**Comment by itsbumble** [comment]
wait what nevermind

**Comment by LambdAurora** [comment]
No it's just that version of LambdaBetterGrass which is incompatible
Older versions of LBG and LambDynamicLights will work fine.

**Comment by itsbumble** [comment]
oh okay pretty weird. its kind of ironic that someones mods are incompatible with each other but alright ill try an older version

**Comment by LambdAurora** [comment]
It's because I rewrote the GUI library I use and it broke stuff and LambdaControls is still waiting on an update from my end but I miss motivation.

**Comment by itsbumble** [comment]
indium doesnt work with the older versions i dont think, ill just need to wait i guess

**Comment by itsbumble** [comment]
Also I know this is a little bit unrelated, but Aurora keystrokes /keystrokes doesn't work

**Comment by LambdAurora** [comment]
Fixed in [LambdaControls 1.6.0](https://github.com/LambdAurora/LambdaControls/releases/tag/1.6.0-1.16).
