### ISSUE TITLE
controller controls aren't saved between sessions

### ISSUE THREAD

**Issue by Ulhar** [LambdAurora/LambdaControls#55]
**Describe the bug**
Controller controls aren't saved when exiting the settings menu.

**To Reproduce**
1. Go to LambdaControls Settings > Controller Controls
2. Rebind any button (for example, bind Jump to LT)
3. Exit the settings menu
4. Restart Minecraft, repeat step 1
5. Observe the binding being the same as before you started

**Expected behavior**
Rebinding a control persists between sessions.

**Desktop (please complete the following information):**
 - OS: Linux [Ubuntu 20.04]
 - Minecraft: 1.16.5
 - Fabric: 0.32.5+1.16
 - Mods: Attached as [mods.txt][] due to longevity (don't know which ones are actually relevant)
 - Version: 1.6.0
 - Branch: 1.16

[mods.txt]: https://github.com/LambdAurora/LambdaControls/files/6412797/mods.txt

**Additional context**
If the configuration file is edited manually, the mod will observe the rebinds, as expected.

**Comment by LambdAurora** [comment]
Fixed in e652390.
