### ISSUE TITLE
Controller loses cursor focus

### ISSUE THREAD

**Issue by ClaudiusMinimus** [LambdAurora/LambdaControls#6]
**Describe the bug**
When using the cursor in an inventory, if the cursor is outside the inventory area, then the controller loses cursor focus and I have to use my mouse to regain control of the cursor. When the inventory is closed, then the controller regains control of the cursor.

**To Reproduce**
 - Open any inventory
 - Move the cursor to the edge of the inventory (outside the inventory slots)
 - Controller loses control of the cursor

**Expected behavior**
The controller should maintain control of the cursor regardless of the screen position of the cursor.

**Screenshots**
Please note the highlighted slot in the inventory. With the cursor in this position (on any inventory edge or boundary), the controller loses control of the cursor
![2019-12-28_19 12 50](https://user-images.githubusercontent.com/17887664/71551483-20cf7c00-29a6-11ea-97c3-6fc8c8382a63.png)

**Desktop (please complete the following information):**
 -OS: Windows 10
 - Minecraft 1.15.1
 - Fabric [e.g. fabric 0.7.2+build.175]
 - Mods appleskin-/mc1.15-fabric-1.0.8, CHAS+v1.3+for+1.15, expandedstorage-3.8.33+1.15-pre6, Experience-Container-1.4, extra-pressure-plates-1.1.3, Fabric_RFTLBPlus1.4.4, fabric-api-0.4.24+build.279-1.15, fabric-furnaces_1.15pre4-1.2.0, fabricmod_VoxelMap-1.9.14_for_1.15.1, farmcraft-v1.0.1-build-3-19w41a, grid-1.15-fabric0.4.23-1.5, Hwyla-fabric-1.15-pre4-1.9.19-70, i-need-keybinds-0.2.1-unstable.201912010804, InventorySorter-1.6.1, Just_Another_Redstone_Gate_Mod-1.1.1, lambdacontrols-1.0.1-fabric1.15, LightOverlay-4.1-unstable.201912010451,  mamiyaotaru (folder), Materialisation-2.0.0-alpha.3, modmenu-1.8.2+build.18, Mo-Glass-v1.1-MC1.15, moreberries-1.2.3, mousewheelie-1.3.9+1.15-pre5, RebornCore-1.15-4.0.25+build.28, RoughlyEnoughItems-3.2.20, simpleteleporters-2.2.0-1.15, spiketraps-2.0, tdnf-mc115-1.8.69, TechReborn-1.15-3.0.26+build.35, tinyfuel-fabric-0.2.0, toolbuilder-1.15.3, useful_backpacks-1.15.1-1.8.1.49

 - lambdacontrols-1.0.1-fabric1.15
 - Branch [e.g. dev]

**Additional context**
Thanks for a great mod!

**Comment by LambdAurora** [comment]
Hello, sorry for the delay, but does the bug is still there in version 1.1.0?

If yes, can you provide a video? as I don't understand correctly what's the problem is.
