### ISSUE TITLE
[FR] Toggle Shift

### ISSUE THREAD

**Issue by Romvnly-Gaming** [LambdAurora/LambdaControls#70]
**Is your feature request related to a problem? Please describe.**
When shifting, on bedrock you're automatically shifting until you press shift again.

**Describe the solution you'd like**
Add Toggle Shift into LambdaControls for natural bedrock behavior without another mod needed.
**Describe alternatives you've considered**
Toggle Shift Mod

**Additional context**
![image](https://user-images.githubusercontent.com/62443489/126831486-0614aef1-5286-4ead-a473-ef6b75a8d7b6.png)
![image](https://user-images.githubusercontent.com/62443489/126831500-33dd24b3-d0b8-4d7e-83db-884305d09ec6.png)

**Comment by LambdAurora** [comment]
It's... a Vanilla feature in the Accessibility screen?

**Comment by Romvnly-Gaming** [comment]
![javaw_tPSXhsnZic](https://user-images.githubusercontent.com/62443489/126831764-e240faa6-4ae3-45b7-8c63-6cddc500870d.png)

https://user-images.githubusercontent.com/62443489/126831768-6b63ebfa-c0ab-4061-8782-0cda7efa7c6b.mp4

**Comment by LambdAurora** [comment]
In the accessibility screen it's called "Sneak".

**Comment by Romvnly-Gaming** [comment]
Look at my first screenshot, I already have it on hold

**Comment by LambdAurora** [comment]
And your issue is about it having it on toggle?

**Comment by Romvnly-Gaming** [comment]
My bad - I can't read the UI to tell that Hold means I need to hold it and Toggle means it toggles. I am the best at Minecraft.
