### ISSUE TITLE
Let optifine and optifabric work on this mod

### ISSUE THREAD

**Issue by gamemaster64665** [LambdAurora/LambdaControls#77]
Let optifine and optifabric work on this mod

**Comment by gamemaster64665** [comment]
Let optifine and optifabric work on this mod

**Comment by gamemaster64665** [comment]
Let optifine and optifabric work on this mod

**Comment by gamemaster64665** [comment]
Let optifine and optifabric work on this mod

**Comment by gamemaster64665** [comment]
i will hack your account if you dont

**Comment by LambdAurora** [comment]
lol, good luck harassing people who make mods in their free time for their own enjoyment.
