### ISSUE TITLE
Please add Bedrock Style Block placing & Creative flight behavior

### ISSUE THREAD

**Issue by Mhowser** [LambdAurora/LambdaControls#8]
Video: https://streamable.com/bwspq

**Is your feature request related to a problem? Please describe.**
It would be very good to have the block placing behavior and the creative flight behavior that Bedrock edition has, since Bedrock has platforms that use controllers naturally. 

**Describe the solution you'd like**
- [x]  Ability to place block in front of player.
- [x]  Fast block placing / destroying based on players speed and direction.
- [x]  Creative mode flight has little to no inertia / drifting. ( you could probably shorten the normal drift duration so it matches.)

It would also be great if these mechanics were in the settings menu so users can choose which feature they need individually.

**Comment by LambdAurora** [comment]
Everything has been implemented in 1.2.0 and 1.3.0.
