### ISSUE TITLE
I can't set my controls in 1.18

### ISSUE THREAD

**Issue by ZaneFlynt01** [LambdAurora/LambdaControls#83]
I downloaded the 1.17/1.18 version of the mod, but I can't get the controls menu to work when playing on 1.18 and I want to know what to do for it.

**Comment by LambdAurora** [comment]
Use ModMenu to access it, a full update shall come when I have time.

**Comment by ZaneFlynt01** [comment]
I tried that and nothing happened but ok-...

**Comment by LambdAurora** [comment]
> I tried that and nothing happened but ok-...

Did you open ModMenu, then clicked on LambdaControls, then on the gear button on the right? It should display the settings of the mod.
