### ISSUE TITLE
add arrows like in Minecraft Bedrock to navigate with a touch screen

### ISSUE THREAD

**Issue by Lolothepro** [LambdAurora/LambdaControls#86]
As a touchscreen laptop user, I find it a shame that there is no java alternative for this

![image](https://user-images.githubusercontent.com/68275908/147572615-5fbc75cf-acb2-4c3b-9b7f-dfd8f37f88ca.png)

There is this mod, but it is old, for forge, and in 1.12.2
https://github.com/Aang23/MC-TouchControls

**Comment by LambdAurora** [comment]
This mod had touchscreen stuff a long while ago, but it ended up not being possible at all due to the terrible touchscreen capability of desktop operating systems.

**Comment by Lolothepro** [comment]
![image](https://user-images.githubusercontent.com/68275908/147744340-4bd4db5a-7f03-4a54-82e9-08e55a0509c3.png)

I just read the readme, and I have the impression that it is not up to date

**Comment by LambdAurora** [comment]
If I remember correctly, I technically haven't removed the code for it, it's just inaccessible.

The issue that I encountered with touchscreen is, well, on desktop it considers it a single pointer: the mouse, so you can't use multiple fingers at once, or you would need to access some very low-level, potentially breaking libraries to hack into the system to just make it work.
So yeah, not worth it imo.
