### ISSUE TITLE
Issues with the repositories

### ISSUE THREAD

**Issue by Undercoverer** [LambdAurora/LambdaControls#88]
**The main issues are that the repository provided does not match to the jitpack repository** 
```
<dependency>
  <groupId>dev.lambdaurora</groupId>
  <artifactId>lambdacontrols</artifactId>
  <version>1.7.1+1.17</version>
</dependency>
```
versus the actual
```
<dependency>
    <groupId>com.github.lambdaurora</groupId>
    <artifactId>lambdacontrols</artifactId>
    <version>1.6.0-1.16</version>
</dependency>
```
and that the version provided does not actually exist. 

The most recent working version is 1.6.0-1.16

**Screenshots**

![image](https://user-images.githubusercontent.com/53386175/148702070-381e4ab4-b14c-4fed-8f67-4a05efebeaf9.png)

![image](https://user-images.githubusercontent.com/53386175/148702097-d5fd80c5-66f8-46bd-8582-a09687bf3293.png)

**Comment by LambdAurora** [comment]
https://maven.gegy.dev/releases/dev/lambdaurora/lambdacontrols

Jitpack is bad.
